import { Footer } from '../../components/Footer'
import { Navigation } from '../../components/Navigation'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col w-screen h-screen bg-secondary'>
          <Navigation />
          <div className='flex-grow flex justify-center w-full'>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
